name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions
env:
  GITHUB_ACTIONS: "pull request"
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}
jobs:
  github-task-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show GITHUB_ACTIONS
        run: echo "GITHUB_ACTIONS - ${{ env.GITHUB_ACTIONS }}"
      - name: Show branch and repo
        run: echo "Name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
      - name: Show event
        run: echo "Workflow was triggered by event - ${{ github.event_name }}"
