name: CI

run-name: ${{ github.actor }} is testing out GitHub Actions

env:
  GITHUB_ACTIONS: pull request

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "github-task-job"
  github-task-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB_ACTIONS - ${{ env.GITHUB_ACTIONS }}"
      - run: echo "Name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
      - run: echo "Workflow was triggered by event - ${{ github.event_name }}"
